### ISSUE TITLE
In EBU-TT-D examples layout region "bottom" is actually at the top

### ISSUE THREAD

**Issue by charlesritchea** [IRT-Open-Source/irt-ebu-tt-d-application-samples#14]
The tts:origin percentages start at the top-left, so that the "10% 10% defined for "bottom" is actually in the top left of the screen.

From the spec at https://tech.ebu.ch/docs/tech/tech3380.pdf

> The x and y coordinates of the top left corner of a region with respect to the root 
> container region. **The (0, 0) coordinate shall be assumed to be the top left** corner 
> of the root container region.

> Example:
> With tts:origin=”20% 80%”
> the top left corner of the region is shifted 20% of 
> the root container region width **to the right** and 80% o
> f the root container region 
> height **to the bottom**.

**Comment by spoeschel** [comment]
It is true that the `tts:origin` origin refers to the top left corner of the screen. Together with the `tts:extent` attribute, a reasonable region spans over the screen. We usually use a `10% 10%` origin and a `80% 80%` extent here, resulting in a centered region of 80% size in horizontal as well as in vertical direction.

However these two attributes don't specify how the actual content within the region is aligned - this is done by the `tts:displayAlign` attribute: In case of the regions called `bottom`, the actual subtitle text is aligned at the bottom of the region, because this attribute is set to `after`. For top alignment, this attribute would have been set to `before`. Please note that the meaning of `before`/`after` depends on the writing direction set by the document.

**Comment by spoeschel** [comment]
@novaterata
I'm not sure if you have further questions regarding this. If not, I will close the issue within the next few days.

**Comment by andreastai** [comment]
Closing this issue as commenter did not respond and issue was clarified by @spoeschel. @novaterata Please re-open if you think the issue was not resolved.
